### PR TITLE
Markup and Style page

### PR DESCRIPTION
**Pull request by Oluwadamilareolusakin**
I wrote the markup and style the page after the example and specifications

### CODE REVIEW

**Comment by samgaco** [comment]
Hi!

I can tell you put a lot of effort on this one, and it is looking nice :raised_hands: , anyways there are some things to address:

* h1.png and h2.png should be background images of a div container and they should be wrapped as anchor links. (In the original site you can see that you are able to click on them)

* You forgot to add the "Watch the "You Verse" film and explore the stories" below h2.png, it should be anchored as well, with a hoover underline and a "play" button at the right side.

* The images p1.jpg, p2.jpg, p3.jpg, and p4.jpg should be wrapped within the footer tag and they should be background images of their div containers, they should be anchored as well. (Again you can see that in the original site you are able to click on them)

* I like the description you wrote in the Readme file, You could also add a live demo of the website, you can use https://raw.githack.com/

* If you check the live version of the website you can see that at the leftmost part of the website the letters "Empty header" appear, try to delete them.

* For the last, in your input element, you should enable the focus effect ( https://www.w3schools.com/cssref/sel_focus.asp )

That's it, try to correct these things :pray: and submit back for review. You are doing very well so far, so working on these things will allow you too polish on your front end skills even more. :muscle:

**Comment by samgaco** [comment]
Hi!

I can tell you put a lot of effort on this one, and it is looking nice :raised_hands: , anyways there are some things to address:

* h1.png and h2.png should be background images of a div container and they should be wrapped as anchor links. (In the original site you can see that you are able to click on them)

* You forgot to add the "Watch the "You Verse" film and explore the stories" below h2.png, it should be anchored as well, with a hoover underline and a "play" button at the right side.

* The images p1.jpg, p2.jpg, p3.jpg, and p4.jpg should be wrapped within the footer tag and they should be background images of their div containers, they should be anchored as well. (Again you can see that in the original site you are able to click on them)

* I like the description you wrote in the Readme file, You could also add a live demo of the website, you can use https://raw.githack.com/

* If you check the live version of the website you can see that at the leftmost part of the website the letters "Empty header" appear, try to delete them.

* For the last, in your input element, you should enable the focus effect ( https://www.w3schools.com/cssref/sel_focus.asp )

That's it, try to correct these things :pray: and submit back for review. You are doing very well so far, so working on these things will allow you too polish on your front end skills even more. :muscle:

**Comment by samgaco** [comment]
Hi again!

Well done :+1:, you've implemented all the things I talked to you about perfectly. Hence, your project is approved. You can merge to the master branch and submit the Project completion form :point_up_2: .


Anyhow, let me give you two suggestions :v: :

1. You could also add a live-demo of the site to your Readme file ( https://rawcdn.githack.com/Oluwadamilareolusakin/Apple-website-replica/9eedb065207fd89bc99cab52ca2e994c2cea9f19/index.html ) that would make it look more professional.

2. You could implement the icon after the "explore the stories" bit with fontawesome ( https://fontawesome.com/icons/play?style=solid ) you can see how to use it here: https://fontawesome.com/how-to-use/on-the-web/setup/getting-started

Anyways, congratulations again on finishing your first solo project. Keep up the good work :muscle: .

**Comment by Oluwadamilareolusakin** [comment]
Thank you @samgaco I will also implement those changes. I am grateful for your thoughtfulness

**Pull request merged**
